"""Sync thin-slicing increments into story-graph.json using story-graph-ops."""
import sys
sys.path.insert(0, r'C:\dev\agilebydesign-skills\skills\story-driven-delivery\story-graph-ops\scripts')

from story_graph_ops.nodes import StoryMap  # nodes.StoryMap — tracks path, save() takes no args

GRAPH = r'C:\dev\mm3e-online-holistic\docs\story-graph.json'

INCREMENTS = [
    {
        "name": "Increment 1: Bare-Bones Playable Hero",
        "priority": 1,
        "goal": "A GM can set a series Power Level, a player can build a stripped-down hero (abilities + defenses only, one motivation), and the pair can run a basic trait check or resistance check and resolve the outcome.",
        "stories": [
            "Set Series Power Level",
            "Derive Starting Power Points from Power Level",
            "Spend Power Points on Ability Ranks",
            "Spend Power Points on Defense Ranks",
            "Validate Power Points Total Balance",
            "Enforce Attack and Effect Cap",
            "Enforce Dodge and Toughness Cap",
            "Enforce Parry and Toughness Cap",
            "Enforce Fortitude and Will Cap",
            "Develop Hero Concept",
            "Choose Motivation Complication",
            "Validate Minimum Complication Requirement",
            "Approve Completed Hero for Play",
            "Set Ability Rank",
            "Derive Base Defense Rank from Ability",
            "Make Trait Check",
            "Grade Check Result by Degree",
            "Make Resistance Check Against Effect",
            "Roll Initiative Check",
            "Determine Turn Order from Initiative Results",
            "Take Standard Action on Turn",
            "Take Move Action on Turn",
        ],
    },
    {
        "name": "Increment 2: Affliction, Damage, and Full Combat Loop",
        "priority": 2,
        "goal": "Players can configure Affliction and Damage power effects, run a complete combat round with conditions applied and recovered, and resolve dying/stabilization.",
        "stories": [
            "Make Opposed Check Against Target Trait",
            "Make Team Check with Combined Effort",
            "Make Active Defence Check",
            "Make Close Attack Check Against Parry",
            "Make Ranged Attack Check Against Dodge",
            "Resolve Attack Check Against Defense Class",
            "Register Natural 1 as Automatic Miss",
            "Select Affliction Effect and Configure Condition Set",
            "Resolve Affliction Resistance Check and Apply Condition Degree",
            "Recover from Affliction Condition at End of Turn",
            "Select Damage Effect for Close Combat",
            "Select Blast Effect for Ranged Energy Attack",
            "Resolve Damage Resistance Check and Apply Damage Condition",
            "Apply Condition to Character",
            "Supersede Condition in Chain",
            "Roll Resistance Check Against Ongoing Effect to Remove Conditions",
            "Remove Condition When Source Effect Ends",
            "Resolve Toughness Resistance Check Against Damage",
            "Apply Cumulative Toughness Penalty",
            "Apply Damage Condition by Degree of Failure",
            "Transition Incapacitated Target to Dying",
            "Apply Minion Defeat Rule on Any Resistance Failure",
            "Recover from Damage in Conflict",
            "Remove Damage Condition After Rest",
            "Resolve Ongoing Effect Resistance Check at End of Turn",
            "Exchange Standard Action for Additional Move Action",
            "Take Free Action During Turn",
            "Take Reaction Outside Turn",
            "Determine Critical Hit When Total Meets Defense",
            "Apply Critical Hit Effect Choice",
            "Defend Against Incoming Attacks",
            "Roll Fortitude Check to Stabilize While Dying",
            "Stabilize Dying Ally with Treatment Check",
        ],
    },
    {
        "name": "Increment 3: Skills, Advantages, and Full Ability Configuration",
        "priority": 3,
        "goal": "Players can spend PP on skills and advantages during construction, make skill checks in play, use combat and fortune advantages, and handle ability edge cases (absent, debilitated, enhanced).",
        "stories": [
            "Spend Power Points on Skill Ranks",
            "Spend Power Points on Advantages",
            "Enforce Skill Modifier Cap",
            "Apply Trade-Off within Limit Pair",
            "Assign Skill Ranks",
            "Enforce Skill Modifier Limit",
            "Make Skill Check",
            "Apply Critical Success on Natural 20",
            "Resolve Untrained Skill Attempt",
            "Apply Skill Mastery Routine Result",
            "Apply Circumstance Modifier to Skill Check",
            "Bluff Target with Deception",
            "Coerce Target with Intimidation",
            "Demoralize Opponent with Intimidation",
            "Improve NPC Attitude with Persuasion",
            "Resist Interaction Skill with Insight",
            "Climb Surface with Athletics",
            "Jump with Athletics",
            "Hide from Observer with Stealth",
            "Add Close Combat Rank to Attack Check",
            "Add Ranged Combat Rank to Attack Check",
            "Purchase Advantage Rank",
            "Validate Power Point Cost for Advantage",
            "Enforce Power Level Cap on Attack Advantage Bonus",
            "Apply Ranked Attack Bonus to Close or Ranged Attack Check",
            "Apply Initiative Bonus from Improved Initiative",
            "Re-Roll Die Using Luck Rank",
            "Enforce Luck Session-Use Limit and Refresh at Adventure Start",
            "Inspire Allies with Hero Point",
            "Use Any Skill Untrained via Jack of All Trades",
            "Make Routine Skill Check Under Pressure via Skill Mastery",
            "Persist Advantage Selections on Character Sheet",
            "Track Luck Rank Uses per Session",
            "Designate Ability Rank Portion as Enhanced",
            "Cascade Trait Changes on Ability Rank Alteration",
            "Enforce Ability Rank Ceiling per Power Level",
            "Increase Defense Rank Above Ability Base",
            "Enforce Toughness Increase Restriction",
            "Derive Initiative Modifier from Agility",
            "Apply Absent Ability Capability Restrictions",
            "Apply Debilitated Ability Condition Effects",
            "Clear Debilitated State When Ability Rank Recovers",
        ],
    },
    {
        "name": "Increment 4: Attack Powers — Ranged, Weakening, Nullify",
        "priority": 4,
        "goal": "Players can configure Blast, Deflect, Weaken, and Nullify effects with the full Power Cost Formula (extras and flaws) and resolve their resistance checks in play.",
        "stories": [
            "Spend Power Points on Powers",
            "Select Deflect Effect for Ranged Protection",
            "Select Nullify Effect and Define Target Descriptor",
            "Select Weaken Effect and Define Target Trait",
            "Resolve Weaken Resistance Check and Reduce Target Trait",
            "Recover Weakened Trait at One Point per Round",
            "Resolve Nullify Opposed Check Against Target Effect Rank",
            "Apply Extra Modifier to Increase Per-Rank Cost",
            "Apply Flaw Modifier to Decrease Per-Rank Cost",
            "Prevent Per-Rank Cost Dropping Below Minimum via Flaw",
            "Apply Flat Cost Modifier to Power",
            "Apply Linked Effect Modifier to Power",
            "Assign Origin Descriptor to Power Set",
            "Assign Source Descriptor to Power Effect",
            "Assign Result Descriptor to Power Effect",
            "Match Power Descriptor Against Immunity Effect Coverage",
            "Match Power Descriptor Against Nullify Effect Target",
            "Approve Descriptor Interaction Between Powers",
        ],
    },
    {
        "name": "Increment 5: Defense and Recovery Powers",
        "priority": 5,
        "goal": "Players can configure Protection, Immunity, Regeneration, and Immortality effects; the system resolves immunity checks and regeneration recovery phases in play.",
        "stories": [
            "Select Protection Effect for Toughness Bonus",
            "Select Immunity Effect and Define Covered Effect Set",
            "Configure Partial Immunity for Half-Effect Protection",
            "Select Regeneration Effect for Progressive Damage Recovery",
            "Select Immortality Effect for Death Recovery",
            "Apply Immunity Check Against Matching Power Descriptor",
            "Remove Toughness Penalty via Regeneration Recovery Phase",
            "Remove Damage Condition via Regeneration Condition Phase",
            "Recover from Death via Immortality After Time Elapses",
        ],
    },
    {
        "name": "Increment 6: Mobility, Sensory, and Power Arrays",
        "priority": 6,
        "goal": "Players can configure movement powers, sensory powers, and organize powers into standard and dynamic arrays with proper mutual-exclusivity and switching rules.",
        "stories": [
            "Select Flight Effect for Aerial Movement",
            "Select Speed Effect for Ground Velocity Enhancement",
            "Select Teleport Effect for Instantaneous Relocation",
            "Select Movement Effect and Choose Special Movement Mode",
            "Calculate Flight Speed Rank from Effect Rank",
            "Validate Teleport Destination as Known or Accurately Sensed",
            "Select Senses Effect and Allocate Sense Enhancements",
            "Select Concealment Effect and Define Affected Sense Type",
            "Build Power Array with Base Effect",
            "Add Alternate Effect to Array within Primary Effect Cost Limit",
            "Add Dynamic Alternate Effect for Simultaneous Use",
            "Switch Active Effect in Array as Free Action",
            "Enforce Array Mutual Exclusivity Rule for Non-Dynamic Effects",
            "Propagate Array Disable Equally to All Alternate Effects",
            "Reallocate Power Points Among Dynamic Array Effects per Turn",
            "Enforce Dynamic Effect Point Total Against Array Pool Size",
        ],
    },
    {
        "name": "Increment 7: Equipment, Devices, and Vehicles",
        "priority": 7,
        "goal": "Players can allocate Equipment Points, acquire weapons/armor/gear, build Devices (removable powers with cost discounts), invent temporary devices, and configure team vehicles and headquarters.",
        "stories": [
            "Allocate Equipment Points to Gear",
            "Enforce Equipment Point Budget from Rank",
            "Pay Equipment Points for Item",
            "Enforce Equipment Bonus Non-stacking",
            "Build Alternate Equipment Array",
            "Select Simple Melee Weapon",
            "Select Projectile Weapon",
            "Select Energy Weapon",
            "Add Weapon Accessory",
            "Select Modern Armor Type",
            "Select Shield Type",
            "Apply Active Defense Bonus from Shield",
            "Cap Equipment Toughness at Power Level",
            "Purchase Communications Device",
            "Purchase Transportation Device",
            "Build Utility Belt Array",
            "Designate Power as Removable Device",
            "Designate Power as Easily Removable Device",
            "Calculate Reduced Cost from Removable Flaw",
            "Build Battlesuit Power Armor Device",
            "Build Costume Device",
            "Remove Powers When Device Taken Away",
            "Define Invention Effect and Point Cost",
            "Make Design Check in Secret",
            "Complete Construction Check",
            "Use Invention for One Scene",
            "Jury-Rig Device by Spending Hero Point",
            "Select Vehicle Size Category",
            "Derive Base Vehicle Traits from Size",
            "Select Vehicle Speed Effect",
            "Select Headquarters Size Category",
            "Add Defense System Feature",
            "Add Workshop or Laboratory Feature",
            "Pool Equipment Points for Team Headquarters",
        ],
    },
]

sm = StoryMap.from_json_file(GRAPH)  # stores path internally — save() writes back to same path

# Clear existing increments
for inc in list(sm.increments):
    sm.remove_increment(inc.name)

# Add all increments with stories
for inc_data in INCREMENTS:
    sm.add_increment(inc_data["name"])
    inc = sm.increments.find_by_name(inc_data["name"])
    inc.goal = inc_data["goal"]
    for story in inc_data["stories"]:
        inc.add_story(story)

sm.save()
print(f"Saved {len(list(sm.increments))} increments to {GRAPH}")
for inc in sorted(sm.increments, key=lambda i: i.priority):
    print(f"  {inc.name}: {len(inc.stories)} stories")
